#!/bin/bash
# Alejandro Martinez Carcedo

# Definir variables
nombre_vpc="pruebas11"
cidr_block_vpc="10.0.0.0/16"

# Crear VPC
vpc_id=$(aws ec2 create-vpc --cidr-block $cidr_block_vpc --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value='$nombre_vpc'}]' --output json | jq -r '.Vpc.VpcId')
echo "VPC creada con ID: $vpc_id"

# Habilitar la asignación automática de direcciones IP
aws ec2 modify-vpc-attribute --vpc-id $vpc_id --enable-dns-support "{\"Value\":true}"
aws ec2 modify-vpc-attribute --vpc-id $vpc_id --enable-dns-hostnames "{\"Value\":true}"

# Crear subredes públicas
cidr_block_pub1="10.0.1.0/24"
cidr_block_pub2="10.0.2.0/24"

subnet_pub1_id=$(aws ec2 create-subnet --vpc-id $vpc_id --cidr-block $cidr_block_pub1 --availability-zone us-east-1a --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=publica11}]' --output json | jq -r '.Subnet.SubnetId')
subnet_pub2_id=$(aws ec2 create-subnet --vpc-id $vpc_id --cidr-block $cidr_block_pub2 --availability-zone us-east-1b --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=publica12}]' --output json | jq -r '.Subnet.SubnetId')

echo "Subredes públicas creadas con IDs: $subnet_pub1_id y $subnet_pub2_id"

# Crear subredes privadas
cidr_block_priv1="10.0.3.0/24"
cidr_block_priv2="10.0.4.0/24"

subnet_priv1_id=$(aws ec2 create-subnet --vpc-id $vpc_id --cidr-block $cidr_block_priv1 --availability-zone us-east-1a --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=privada11}]' --output json | jq -r '.Subnet.SubnetId')
subnet_priv2_id=$(aws ec2 create-subnet --vpc-id $vpc_id --cidr-block $cidr_block_priv2 --availability-zone us-east-1b --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=privada12}]' --output json | jq -r '.Subnet.SubnetId')

echo "Subredes privadas creadas con IDs: $subnet_priv1_id y $subnet_priv2_id"

# Crear tabla de enrutamiento pública
route_table_pub_id=$(aws ec2 create-route-table --vpc-id $vpc_id --tag-specifications 'ResourceType=route-table,Tags=[{Key=Name,Value=publica-route-table}]' --output json | jq -r '.RouteTable.RouteTableId')
echo "Tabla de enrutamiento pública creada con ID: $route_table_pub_id"

# Asociar tabla de enrutamiento pública con subredes públicas
aws ec2 associate-route-table --subnet-id $subnet_pub1_id --route-table-id $route_table_pub_id
aws ec2 associate-route-table --subnet-id $subnet_pub2_id --route-table-id $route_table_pub_id

# Crear gateway de internet
internet_gateway_id=$(aws ec2 create-internet-gateway --tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=gateway-pruebas11}]' --output json | jq -r '.InternetGateway.InternetGatewayId')
echo "Gateway de internet creado con ID: $internet_gateway_id"

# Adjuntar gateway de internet a la VPC
aws ec2 attach-internet-gateway --vpc-id $vpc_id --internet-gateway-id $internet_gateway_id

# Añadir ruta pública a la tabla de enrutamiento
aws ec2 create-route --route-table-id $route_table_pub_id --destination-cidr-block 0.0.0.0/0 --gateway-id $internet_gateway_id

# Crear tabla de enrutamiento privada
route_table_priv_id=$(aws ec2 create-route-table --vpc-id $vpc_id --tag-specifications 'ResourceType=route-table,Tags=[{Key=Name,Value=privada-route-table}]' --output json | jq -r '.RouteTable.RouteTableId')
echo "Tabla de enrutamiento privada creada con ID: $route_table_priv_id"

# Asociar tabla de enrutamiento privada con subredes privadas
aws ec2 associate-route-table --subnet-id $subnet_priv1_id --route-table-id $route_table_priv_id
aws ec2 associate-route-table --subnet-id $subnet_priv2_id --route-table-id $route_table_priv_id

# Crear Elastic IP para el Gateway NAT
nat_eip_allocation_id=$(aws ec2 allocate-address --domain vpc --query 'AllocationId' --output text)

# Crear Gateway NAT para la subred privada12
nat_gateway_id=$(aws ec2 create-nat-gateway --subnet-id $subnet_priv2_id --allocation-id $nat_eip_allocation_id --output json | jq -r '.NatGateway.NatGatewayId')
echo "Gateway NAT creado con ID: $nat_gateway_id"

# Imprimir información final
echo "VPC con subredes, tablas de enrutamiento y Gateway NAT creados exitosamente."
