#!/bin/bash

sudo ufw disable
sudo ufw --force reset

sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow 3478
sudo ufw allow 3479
sudo ufw allow 8448
sudo ufw deny http

sudo ufw deny out 25

sudo ufw enable
